[package]
name = "rtsp-webcam-server"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = { version = "0.92.0", features = ["clang-runtime"] }


[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"